### ISSUE TITLE
OAI-PMH protocol date granularity ignored

### ISSUE THREAD

**Issue by paulo-graca** [lareferencia/lareferencia-core-lib#3]
We are harvesting from:
https://scielo.pt/oai/scielo-oai.php?verb=Identify

That specifies which granularity it's used:
`<granularity>YYYY-MM-DD</granularity>`

The protocol specifies that UTCdatetime it's used and «All repositories must support YYYY-MM-DD. A repository that supports YYYY-MM-DDThh:mm:ssZ should indicate so in the [Identify](http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify) response.»
http://www.openarchives.org/OAI/openarchivesprotocol.html#Dates

But when looking at logs, **incremental harvesting** tries to do a GET with a different granularity, resulting in an BadRequest error.
https://scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-07T11:33:40Z&metadataPrefix=oai_dc

**Comment by lmatas** [comment]
Good point. We need to implement an Identify call before starting the
harvesting process in order to fetch de granularity. Then apply that format
to the ListRecord call. I need to plan when to implement this and test it.
I will keep you updated. Thank you
Lautaro Matas

**Comment by paulo-graca** [comment]
closed with #4
